//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeniplasApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeniplasEntities : DbContext
    {
        public BeniplasEntities()
            : base("name=BeniplasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradors> Administradors { get; set; }
        public virtual DbSet<Empleadoes> Empleadoes { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Gerentes> Gerentes { get; set; }
        public virtual DbSet<RegistroAperturaAdministradors> RegistroAperturaAdministradors { get; set; }
        public virtual DbSet<RegistroAperturaEmpleadoes> RegistroAperturaEmpleadoes { get; set; }
        public virtual DbSet<RegistroAperturaGerentes> RegistroAperturaGerentes { get; set; }
        public virtual DbSet<Sucursals> Sucursals { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
